"""The NIL edge: the six endpoints, generic across any backend. GENERATED by nilscript scaffold.

Enforces the contract — envelope + bearer auth, no side effects on PROPOSE, idempotent COMMIT, a
real write surfaced as an HMAC-signed EVENT, bare {data} for QUERY. It calls the translation core
(translate.py) and the system client (system.py); it contains no backend specifics. Do not edit —
regenerate with `nilscript scaffold-shim`.
"""

from __future__ import annotations

import hashlib
import hmac
import json
from datetime import UTC, datetime
from typing import Any, Protocol
from uuid import uuid4

from fastapi import Body, FastAPI, Header, HTTPException, Response

from pocketbase_nil_adapter.compensation import COMPENSATIONS, compensate
from pocketbase_nil_adapter.manifest import apply_transport_quirks, overlay_requirements
from pocketbase_nil_adapter.state import ShimState
from pocketbase_nil_adapter.system import SystemClient, SystemError
from pocketbase_nil_adapter.translate import QUERY_VERBS, WRITE_VERBS, entity_ref

NIL = "0.1"
SYSTEM = "pocketbase"


def _now() -> str:
    return datetime.now(UTC).isoformat()


class EventEmitter(Protocol):
    def emit(self, event_envelope: dict[str, Any], sequence: int) -> None: ...


class CapturingEmitter:
    """Test/proof emitter: records pushed events instead of sending them."""

    def __init__(self) -> None:
        self.events: list[tuple[int, dict[str, Any]]] = []

    def emit(self, event_envelope: dict[str, Any], sequence: int) -> None:
        self.events.append((sequence, event_envelope))


class HttpEventEmitter:
    """Real emitter: HMAC-SHA256 over the raw body + a monotonic per-workspace sequence header."""

    def __init__(self, webhook_url: str, secret: str) -> None:
        self._url = webhook_url
        self._secret = secret.encode("utf-8")

    def emit(self, event_envelope: dict[str, Any], sequence: int) -> None:
        import httpx

        raw = json.dumps(event_envelope, separators=(",", ":")).encode("utf-8")
        signature = hmac.new(self._secret, raw, hashlib.sha256).hexdigest()
        httpx.post(
            self._url,
            content=raw,
            headers={
                "Content-Type": "application/json",
                "X-NIL-Signature": signature,
                "X-NIL-Sequence": str(sequence),
            },
            timeout=10.0,
        )


def _envelope(performative: str, env: dict[str, Any], body: dict[str, Any]) -> dict[str, Any]:
    return {
        "nil": NIL,
        "id": uuid4().hex,
        "performative": performative,
        "grant": env.get("grant", ""),
        "workspace": env.get("workspace", ""),
        "ts": _now(),
        "body": body,
    }


def _refusal(env: dict[str, Any], code: str, message: str, field: str | None = None) -> dict[str, Any]:
    body: dict[str, Any] = {"outcome": "refusal", "code": code, "message": message}
    if field is not None:
        body["field"] = field
    return _envelope("PROPOSAL", env, body)


def create_app(client: SystemClient, emitter: EventEmitter, *, bearer: str | None) -> FastAPI:
    app = FastAPI(title="pocketbase-nil-adapter shim", version="0.1.0")
    state = ShimState()
    apply_transport_quirks(client)  # manifest-driven: e.g. drop Expect: 100-continue (plan §4.4)

    def _auth(authorization: str | None) -> None:
        if bearer is None:  # permissive dev wiring behind a trusted gateway
            return
        # constant-time compare — a `!=` would leak the token via timing.
        if not hmac.compare_digest(authorization or "", f"Bearer {bearer}"):
            raise HTTPException(status_code=401, detail="unauthorized")

    @app.post("/nil/v0.1/propose")
    def propose(env: dict[str, Any] = Body(...), authorization: str | None = Header(None)) -> dict[str, Any]:
        _auth(authorization)
        body = env.get("body", {})
        verb_name = body.get("verb")
        args = body.get("args", {}) or {}
        verb = WRITE_VERBS.get(verb_name)
        if verb is None:
            return _refusal(env, "UNSUPPORTED", f"verb not supported by this backend: {verb_name}")
        missing = verb.missing(args)
        if missing:
            return _refusal(env, "INVALID_ARGS", f"missing required arg: {missing[0]}", field=missing[0])
        proposal_id = uuid4().hex[:16]
        state.proposals[proposal_id] = {"verb": verb_name, "args": args}  # NO write — dry-run only
        return _envelope(
            "PROPOSAL",
            env,
            {
                "outcome": "proposal",
                "id": proposal_id,
                "verb": verb_name,
                "tier": verb.tier,
                "preview": verb.preview(args),
                "resolved": args,
                "modifiable": [],
                "expires_at": _now(),
            },
        )

    @app.post("/nil/v0.1/commit")
    def commit(env: dict[str, Any] = Body(...), authorization: str | None = Header(None)) -> dict[str, Any]:
        _auth(authorization)
        body = env.get("body", {})
        key = body.get("idempotency_key", "")
        if key in state.ledger:  # retried COMMIT — replay, no second write
            return _envelope("STATUS", env, {**state.ledger[key], "replayed": True})
        proposal_id = body.get("proposal", "")
        stored = state.proposals.get(proposal_id)
        if stored is None:
            return _refusal(env, "EXPIRED", f"unknown or expired proposal: {proposal_id}")
        verb = WRITE_VERBS[stored["verb"]]
        try:
            # to_native is inside the try so an UNFILLED stub (NotImplementedError) is a clean
            # terminal failure, not a 500 — the conformance proof reads it as non-conformance.
            native = overlay_requirements(stored["verb"], verb.to_native(stored["args"]))  # manifest pre-fill
            # Write-path dispatch by the standard's verb lexicon: delete_* -> DELETE, update_* ->
            # PATCH/UPDATE, everything else (create_/record_/send_/draft_/process_) -> CREATE. The
            # record id for update/delete is the verb's first required arg (e.g. product_id).
            action = stored["verb"].split(".")[-1]
            if action.startswith("delete_"):
                record_id = str(stored["args"].get(verb.required[0], "")) if verb.required else ""
                client.delete(verb.doctype, record_id)
                created = {"name": record_id}
            elif action.startswith("update_"):
                record_id = str(stored["args"].get(verb.required[0], "")) if verb.required else ""
                created = client.update(verb.doctype, record_id, native)
            else:
                created = client.create(verb.doctype, native)  # the real write
        except (SystemError, NotImplementedError) as exc:
            print(f"[shim] WRITE FAILED verb={stored['verb']} -> {exc}", flush=True)
            return _envelope("STATUS", env, {"proposal": proposal_id, "state": "failed_terminal", "replayed": False})
        reversibility = COMPENSATIONS.get(stored["verb"], {}).get("reversibility", "IRREVERSIBLE")
        status_body = {"proposal": proposal_id, "state": "executed", "replayed": False}
        result = {
            "claim": "success",
            "changed": True,
            "verified": True,
            "entity": entity_ref(verb, created),
            "ssot": {"system": SYSTEM, "read_after_write": True},
        }
        comp_block = {"reversibility": reversibility}  # every effect declares its reversibility honestly
        if reversibility != "IRREVERSIBLE":  # mint a reversal handle the owner/agent can ROLLBACK
            comp_token = uuid4().hex[:16]
            state.compensations[comp_token] = {"verb": stored["verb"], "result": {"entity": result["entity"]}}
            comp_block["token"] = comp_token  # token present only when actually reversible
        status_body["compensation"] = comp_block
        result["compensation"] = comp_block
        state.ledger[key] = status_body
        state.executed.add(proposal_id)  # so GET /status reports executed, not just proposed
        sequence = state.next_sequence(env.get("workspace", ""))
        emitter.emit(
            _envelope(
                "EVENT",
                env,
                {"event": "executed", "severity": "info", "proposal": proposal_id, "result": result},
            ),
            sequence,
        )
        return _envelope("STATUS", env, status_body)

    @app.post("/nil/v0.1/query")
    def query(env: dict[str, Any] = Body(...), authorization: str | None = Header(None)) -> dict[str, Any]:
        _auth(authorization)
        body = env.get("body", {})
        verb = QUERY_VERBS.get(body.get("verb"))
        if verb is None:
            raise HTTPException(status_code=404, detail="unknown query verb")
        return {"data": verb.run(client, body.get("args", {}) or {})}  # bare { data }

    @app.get("/nil/v0.1/status/{proposal_id}")
    def status(proposal_id: str, authorization: str | None = Header(None)) -> dict[str, Any]:
        _auth(authorization)
        if proposal_id in state.executed:
            current = "executed"
        elif proposal_id in state.proposals:
            current = "pending"  # proposed, not yet committed
        else:
            current = "expired"
        return _envelope(
            "STATUS",
            {"grant": "", "workspace": ""},
            {"proposal": proposal_id, "state": current, "replayed": True},
        )

    @app.post("/nil/v0.1/rollback")
    def rollback(env: dict[str, Any] = Body(...), authorization: str | None = Header(None)) -> dict[str, Any]:
        # ROLLBACK requests a governed reversal: it never writes. We answer with a PROPOSAL (the
        # compensation preview); committing THAT proposal via /commit executes the reversal — so
        # "no silent write" holds even when undoing. An unmapped (IRREVERSIBLE) effect is refused.
        _auth(authorization)
        body = env.get("body", {})
        token = body.get("compensation_token", "")
        committed = state.compensations.get(token)
        if committed is None:
            return _refusal(env, "COMPENSATION_EXPIRED", f"unknown or expired compensation token: {token}")
        verb_name = committed["verb"]
        try:
            comp_args = compensate(verb_name, committed["result"])
        except NotImplementedError:
            return _refusal(env, "IRREVERSIBLE", f"{verb_name} cannot be reversed")
        comp_verb_name = COMPENSATIONS[verb_name]["verb"]
        comp_verb = WRITE_VERBS.get(comp_verb_name)
        proposal_id = uuid4().hex[:16]
        state.proposals[proposal_id] = {"verb": comp_verb_name, "args": comp_args}  # the reversal, not yet committed
        preview = comp_verb.preview(comp_args) if comp_verb is not None else {"en": f"reverse {verb_name}", "ar": f"عكس {verb_name}"}
        return _envelope(
            "PROPOSAL",
            env,
            {
                "outcome": "proposal",
                "id": proposal_id,
                "verb": comp_verb_name,
                "tier": comp_verb.tier if comp_verb is not None else "HIGH",
                "preview": preview,
                "resolved": comp_args,
                "modifiable": [],
                "expires_at": _now(),
            },
        )

    @app.get("/healthz")
    def healthz() -> Response:
        return Response(status_code=200)

    return app
