"""The NIL edge: the six endpoints, generic across any backend. GENERATED by nilscript scaffold.

Enforces the contract — envelope + bearer auth, no side effects on PROPOSE, idempotent COMMIT, a
real write surfaced as an HMAC-signed EVENT, bare {data} for QUERY. It calls the translation core
(translate.py) and the system client (system.py); it contains no backend specifics. Do not edit —
regenerate with `nilscript scaffold-shim`.
"""

from __future__ import annotations

import hashlib
import hmac
import json
import re
from datetime import UTC, datetime
from typing import Any, Protocol
from uuid import uuid4

from fastapi import Body, FastAPI, Header, HTTPException, Response

from pocketbase_nil_adapter.compensation import COMPENSATIONS, compensate
from pocketbase_nil_adapter.manifest import apply_transport_quirks, overlay_requirements
from pocketbase_nil_adapter.state import ShimState
from pocketbase_nil_adapter.system import SystemClient, SystemError
from pocketbase_nil_adapter.translate import QUERY_VERBS, WRITE_VERBS, entity_ref

NIL = "0.1"
SYSTEM = "pocketbase"


def _now() -> str:
    return datetime.now(UTC).isoformat()


_HTML_TAG = re.compile(r"<[^>]+>")


def _field_landed(actual: Any, intended: Any) -> bool:
    """Did the SSOT actually take the intended value? Tolerates backend normalization but treats
    empty/false-where-a-value-was-intended as a hard miss — the signature of a silently dropped write."""
    if actual == intended:
        return True
    intended_s = str(intended).strip() if intended is not None else ""
    if not intended_s:
        return True
    actual_s = _HTML_TAG.sub("", str(actual if actual not in (None, False) else "")).strip()
    return intended_s == actual_s or intended_s in actual_s


def _verify_write(client: SystemClient, target: str, record_id: str, native: dict[str, Any]) -> list[str]:
    """Read the record back from the SSOT; return written fields that did NOT land (empty => verified)."""
    after = client.get(target, record_id) or {}
    return [field for field, value in native.items() if not _field_landed(after.get(field), value)]


def _resource_phrase(op: str, target: str, args: dict[str, Any]) -> tuple[str, str]:
    """Bilingual preview for a generic resource.* op (no per-verb authoring)."""
    rid = args.get("id", "")
    data = args.get("data") or {}
    if op == "create":
        return f"Create {target} record {data}", f"إنشاء سجل في {target}"
    if op == "update":
        return f"Update {target}/{rid} → {data}", f"تحديث {target}/{rid}"
    return f"Delete {target}/{rid}", f"حذف {target}/{rid}"


_ID_FIELDS = ("code", "name", "slug", "title", "sku", "email")


def _resolve_id(client: SystemClient, target: str, value: str) -> str | None:
    """Accept a real record id OR a human identifier (code/name/…). Returns the real id, or None
    if it can't be resolved to exactly one record — so 'update coupon RESCRUD2' works by code."""
    if not value:
        return None
    if client.get(target, value) is not None:  # already a real record id
        return value
    for field in _ID_FIELDS:  # try resolving the value as a human identifier
        try:
            rows = client.list(target, {field: value})
        except SystemError:
            continue
        hits = [r for r in rows if str(r.get(field, "")) == str(value)]  # exact, not substring
        if len(hits) == 1:
            return str(hits[0].get("id") or hits[0].get("name"))
    return None


class EventEmitter(Protocol):
    def emit(self, event_envelope: dict[str, Any], sequence: int) -> None: ...


class CapturingEmitter:
    """Test/proof emitter: records pushed events instead of sending them."""

    def __init__(self) -> None:
        self.events: list[tuple[int, dict[str, Any]]] = []

    def emit(self, event_envelope: dict[str, Any], sequence: int) -> None:
        self.events.append((sequence, event_envelope))


class HttpEventEmitter:
    """Real emitter: HMAC-SHA256 over the raw body + a monotonic per-workspace sequence header."""

    def __init__(self, webhook_url: str, secret: str) -> None:
        self._url = webhook_url
        self._secret = secret.encode("utf-8")

    def emit(self, event_envelope: dict[str, Any], sequence: int) -> None:
        import httpx

        raw = json.dumps(event_envelope, separators=(",", ":")).encode("utf-8")
        signature = hmac.new(self._secret, raw, hashlib.sha256).hexdigest()
        httpx.post(
            self._url,
            content=raw,
            headers={
                "Content-Type": "application/json",
                "X-NIL-Signature": signature,
                "X-NIL-Sequence": str(sequence),
            },
            timeout=10.0,
        )


def _envelope(performative: str, env: dict[str, Any], body: dict[str, Any]) -> dict[str, Any]:
    return {
        "nil": NIL,
        "id": uuid4().hex,
        "performative": performative,
        "grant": env.get("grant", ""),
        "workspace": env.get("workspace", ""),
        "ts": _now(),
        "body": body,
    }


def _refusal(env: dict[str, Any], code: str, message: str, field: str | None = None) -> dict[str, Any]:
    body: dict[str, Any] = {"outcome": "refusal", "code": code, "message": message}
    if field is not None:
        body["field"] = field
    return _envelope("PROPOSAL", env, body)


def create_app(client: SystemClient, emitter: EventEmitter, *, bearer: str | None) -> FastAPI:
    app = FastAPI(title="pocketbase-nil-adapter shim", version="0.1.0")
    state = ShimState()
    apply_transport_quirks(client)  # manifest-driven: e.g. drop Expect: 100-continue (plan §4.4)

    def _auth(authorization: str | None) -> None:
        if bearer is None:  # permissive dev wiring behind a trusted gateway
            return
        # constant-time compare — a `!=` would leak the token via timing.
        if not hmac.compare_digest(authorization or "", f"Bearer {bearer}"):
            raise HTTPException(status_code=401, detail="unauthorized")

    @app.post("/nil/v0.1/propose")
    def propose(env: dict[str, Any] = Body(...), authorization: str | None = Header(None)) -> dict[str, Any]:
        _auth(authorization)
        body = env.get("body", {})
        verb_name = body.get("verb")
        args = body.get("args", {}) or {}
        # Generic resource.* CRUD (universal): target/id/data come from args, not a per-verb doctype.
        # Works for ANY provisioned target the skeleton exposes — no per-entity verb authoring.
        if isinstance(verb_name, str) and verb_name.startswith("resource."):
            op = verb_name.split(".", 1)[1]
            if op not in ("create", "update", "delete"):
                return _refusal(env, "UNKNOWN_VERB", f"unknown resource op: {op}")
            target = args.get("target")
            if not target:
                return _refusal(env, "INVALID_ARGS", "missing required arg: target", field="target")
            if op in ("update", "delete") and not args.get("id"):
                return _refusal(env, "INVALID_ARGS", "missing required arg: id", field="id")
            if op in ("create", "update") and not isinstance(args.get("data"), dict):
                return _refusal(env, "INVALID_ARGS", "missing required arg: data", field="data")
            if not client.exists(target):
                return _refusal(env, "UPSTREAM_UNAVAILABLE",
                                f"backend target '{target}' is not provisioned on this system")
            pid = uuid4().hex[:16]
            state.proposals[pid] = {"verb": verb_name, "args": args, "resource": True}
            en, ar = _resource_phrase(op, target, args)
            _rtier = {"create": "MEDIUM", "update": "MEDIUM", "delete": "HIGH"}[op]
            emitter.emit(_envelope("EVENT", env, {"event": "proposed", "severity": "info",
                         "proposal": pid, "verb": verb_name, "tier": _rtier,
                         "preview": {"en": en, "ar": ar}}), state.next_sequence(env.get("workspace", "")))
            return _envelope("PROPOSAL", env, {
                "outcome": "proposal", "id": pid, "verb": verb_name,
                "tier": {"create": "MEDIUM", "update": "MEDIUM", "delete": "HIGH"}[op],
                "preview": {"en": en, "ar": ar}, "resolved": args, "modifiable": [], "expires_at": _now()})

        verb = WRITE_VERBS.get(verb_name)
        if verb is None:
            return _refusal(env, "UNKNOWN_VERB", f"verb not supported by this backend: {verb_name}")
        missing = verb.missing(args)
        if missing:
            return _refusal(env, "INVALID_ARGS", f"missing required arg: {missing[0]}", field=missing[0])
        # Preflight (universal): refuse honestly at PROPOSE if the native target isn't provisioned,
        # so the agent learns now instead of a COMMIT-time failure. exists() lives in system.py.
        if not client.exists(verb.doctype):
            return _refusal(env, "UPSTREAM_UNAVAILABLE",
                            f"backend target '{verb.doctype}' is not provisioned on this system")
        proposal_id = uuid4().hex[:16]
        state.proposals[proposal_id] = {"verb": verb_name, "args": args}  # NO write — dry-run only
        # Audit: surface the INTENT (no side effect) so the control plane can show/approve it.
        emitter.emit(_envelope("EVENT", env, {"event": "proposed", "severity": "info",
                     "proposal": proposal_id, "verb": verb_name, "tier": verb.tier,
                     "preview": verb.preview(args)}), state.next_sequence(env.get("workspace", "")))
        return _envelope(
            "PROPOSAL",
            env,
            {
                "outcome": "proposal",
                "id": proposal_id,
                "verb": verb_name,
                "tier": verb.tier,
                "preview": verb.preview(args),
                "resolved": args,
                "modifiable": [],
                "expires_at": _now(),
            },
        )

    @app.post("/nil/v0.1/commit")
    def commit(env: dict[str, Any] = Body(...), authorization: str | None = Header(None)) -> dict[str, Any]:
        _auth(authorization)
        body = env.get("body", {})
        key = body.get("idempotency_key", "")
        if key in state.ledger:  # retried COMMIT — replay, no second write
            return _envelope("STATUS", env, {**state.ledger[key], "replayed": True})
        proposal_id = body.get("proposal", "")
        stored = state.proposals.get(proposal_id)
        if stored is None:
            return _refusal(env, "EXPIRED", f"unknown or expired proposal: {proposal_id}")
        if stored.get("resource"):  # generic CRUD path — dispatch by args.target, synthesize result
            op = stored["verb"].split(".", 1)[1]
            target = stored["args"]["target"]
            rid = str(stored["args"].get("id", ""))
            data = stored["args"].get("data") or {}
            try:
                if op == "create":
                    created = client.create(target, data)
                    rid = str(created.get("id") or created.get("name") or "")
                    # reversal of a create = delete the created record (synthesized, no per-verb authoring)
                    rev_verb, rev_args, rev = "resource.delete", {"target": target, "id": rid}, "REVERSIBLE"
                else:  # update / delete — resolve a real id from id-or-human-identifier first
                    resolved = _resolve_id(client, target, rid)
                    if resolved is None:
                        print(f"[shim] RESOURCE {op}: no record matched '{rid}' in {target}", flush=True)
                        return _envelope("STATUS", env, {"proposal": proposal_id, "state": "failed_terminal", "replayed": False})
                    rid = resolved
                    before = client.get(target, rid) or {}  # before-image → reversible by restore/recreate
                    if op == "update":
                        client.update(target, rid, data)
                        rev_verb, rev_args, rev = "resource.update", {"target": target, "id": rid, "data": before}, "COMPENSABLE"
                    else:  # delete
                        client.delete(target, rid)
                        rev_verb, rev_args, rev = "resource.create", {"target": target, "data": before}, "COMPENSABLE"
            except (SystemError, NotImplementedError) as exc:
                print(f"[shim] RESOURCE WRITE FAILED {stored['verb']} -> {exc}", flush=True)
                return _envelope("STATUS", env, {"proposal": proposal_id, "state": "failed_terminal", "replayed": False})
            comp_block = {"reversibility": rev}
            tok = uuid4().hex[:16]  # ROLLBACK this token to preview the synthesized reversal
            state.compensations[tok] = {"resource": True, "rev_verb": rev_verb, "rev_args": rev_args}
            comp_block["token"] = tok
            if op == "delete":
                unverified, verified = [], client.get(target, rid) is None
            else:
                unverified = _verify_write(client, target, rid, data)
                verified = not unverified
            ssot = {"system": SYSTEM, "read_after_write": True}
            if unverified:
                ssot["unverified_fields"] = unverified
            result = {"claim": "success" if verified else "partial", "changed": True, "verified": verified,
                      "entity": {"type": stored["verb"], "id": rid, "url": f"/{target}/{rid}"},
                      "ssot": ssot, "compensation": comp_block}
            if unverified:
                result["unverified_fields"] = unverified
            status_body = {"proposal": proposal_id, "state": "executed", "replayed": False,
                           "compensation": comp_block, "result": result}
            state.ledger[key] = status_body
            state.executed.add(proposal_id)
            emitter.emit(_envelope("EVENT", env, {"event": "executed", "severity": "info",
                         "proposal": proposal_id, "verb": stored["verb"], "result": result}),
                         state.next_sequence(env.get("workspace", "")))
            return _envelope("STATUS", env, status_body)
        verb = WRITE_VERBS[stored["verb"]]
        try:
            # to_native is inside the try so an UNFILLED stub (NotImplementedError) is a clean
            # terminal failure, not a 500 — the conformance proof reads it as non-conformance.
            native = overlay_requirements(stored["verb"], verb.to_native(stored["args"]))  # manifest pre-fill
            # Write-path dispatch by the standard's verb lexicon: delete_* -> DELETE, update_* ->
            # PATCH/UPDATE, everything else (create_/record_/send_/draft_/process_) -> CREATE. The
            # record id for update/delete is the verb's first required arg (e.g. product_id).
            action = stored["verb"].split(".")[-1]
            if action.startswith("delete_"):
                raw = str(stored["args"].get(verb.required[0], "")) if verb.required else ""
                record_id = _resolve_id(client, verb.doctype, raw) or raw  # accept id or human identifier
                client.delete(verb.doctype, record_id)
                created = {"name": record_id}
            elif action.startswith("update_"):
                raw = str(stored["args"].get(verb.required[0], "")) if verb.required else ""
                record_id = _resolve_id(client, verb.doctype, raw) or raw
                created = client.update(verb.doctype, record_id, native)
            else:
                created = client.create(verb.doctype, native)  # the real write
        except (SystemError, NotImplementedError) as exc:
            print(f"[shim] WRITE FAILED verb={stored['verb']} -> {exc}", flush=True)
            return _envelope("STATUS", env, {"proposal": proposal_id, "state": "failed_terminal", "replayed": False})
        reversibility = COMPENSATIONS.get(stored["verb"], {}).get("reversibility", "IRREVERSIBLE")
        status_body = {"proposal": proposal_id, "state": "executed", "replayed": False}
        fields_written = {} if action.startswith("delete_") else native
        effect_id = str(created.get("id") or created.get("name") or "")
        if action.startswith("delete_"):
            unverified, verified = [], client.get(verb.doctype, effect_id) is None
        elif fields_written and effect_id:
            unverified = _verify_write(client, verb.doctype, effect_id, fields_written)
            verified = not unverified
        else:
            unverified, verified = [], True
        ssot: dict[str, Any] = {"system": SYSTEM, "read_after_write": True}
        if unverified:
            ssot["unverified_fields"] = unverified
        result = {
            "claim": "success" if verified else "partial",
            "changed": True,
            "verified": verified,
            "entity": entity_ref(verb, created),
            "ssot": ssot,
        }
        if unverified:
            result["unverified_fields"] = unverified
        comp_block = {"reversibility": reversibility}  # every effect declares its reversibility honestly
        if reversibility != "IRREVERSIBLE":  # mint a reversal handle the owner/agent can ROLLBACK
            comp_token = uuid4().hex[:16]
            state.compensations[comp_token] = {"verb": stored["verb"], "result": {"entity": result["entity"]}}
            comp_block["token"] = comp_token  # token present only when actually reversible
        status_body["compensation"] = comp_block
        result["compensation"] = comp_block
        status_body["result"] = result  # surface the SSOT entity + system-of-record to the committer
        state.ledger[key] = status_body
        state.executed.add(proposal_id)  # so GET /status reports executed, not just proposed
        sequence = state.next_sequence(env.get("workspace", ""))
        emitter.emit(
            _envelope(
                "EVENT",
                env,
                {"event": "executed", "severity": "info", "proposal": proposal_id,
                 "verb": stored["verb"], "result": result},
            ),
            sequence,
        )
        return _envelope("STATUS", env, status_body)

    @app.post("/nil/v0.1/query")
    def query(env: dict[str, Any] = Body(...), authorization: str | None = Header(None)) -> dict[str, Any]:
        _auth(authorization)
        body = env.get("body", {})
        verb_name = body.get("verb")
        # Generic resource.read (universal): list/inspect any target the skeleton exposes, by
        # optional field match — lets the agent resolve human values → records/ids in realtime.
        if verb_name == "resource.read":
            qargs = body.get("args", {}) or {}
            target = qargs.get("target")
            if not target or not client.exists(target):
                raise HTTPException(status_code=404, detail=f"unknown or unprovisioned target: {target}")
            rows = client.list(target, qargs.get("match") or None)
            return {"data": {"target": target, "count": len(rows), "items": rows}}
        verb = QUERY_VERBS.get(verb_name)
        if verb is None:
            raise HTTPException(status_code=404, detail="unknown query verb")
        return {"data": verb.run(client, body.get("args", {}) or {})}  # bare { data }

    @app.get("/nil/v0.1/status/{proposal_id}")
    def status(proposal_id: str, authorization: str | None = Header(None)) -> dict[str, Any]:
        _auth(authorization)
        if proposal_id in state.executed:
            current = "executed"
        elif proposal_id in state.proposals:
            current = "pending"  # proposed, not yet committed
        else:
            current = "expired"
        return _envelope(
            "STATUS",
            {"grant": "", "workspace": ""},
            {"proposal": proposal_id, "state": current, "replayed": True},
        )

    @app.post("/nil/v0.1/rollback")
    def rollback(env: dict[str, Any] = Body(...), authorization: str | None = Header(None)) -> dict[str, Any]:
        # ROLLBACK requests a governed reversal: it never writes. We answer with a PROPOSAL (the
        # compensation preview); committing THAT proposal via /commit executes the reversal — so
        # "no silent write" holds even when undoing. An unmapped (IRREVERSIBLE) effect is refused.
        _auth(authorization)
        body = env.get("body", {})
        token = body.get("compensation_token", "")
        committed = state.compensations.get(token)
        if committed is None:
            return _refusal(env, "COMPENSATION_EXPIRED", f"unknown or expired compensation token: {token}")
        if committed.get("resource"):  # generic-CRUD reversal — preview the synthesized compensating verb
            rev_verb, rev_args = committed["rev_verb"], committed["rev_args"]
            rop = rev_verb.split(".", 1)[1]
            pid = uuid4().hex[:16]
            state.proposals[pid] = {"verb": rev_verb, "args": rev_args, "resource": True}
            en, ar = _resource_phrase(rop, rev_args["target"], rev_args)
            return _envelope("PROPOSAL", env, {
                "outcome": "proposal", "id": pid, "verb": rev_verb,
                "tier": {"create": "MEDIUM", "update": "MEDIUM", "delete": "HIGH"}[rop],
                "preview": {"en": en, "ar": ar}, "resolved": rev_args, "modifiable": [], "expires_at": _now()})
        verb_name = committed["verb"]
        try:
            comp_args = compensate(verb_name, committed["result"])
        except NotImplementedError:
            return _refusal(env, "IRREVERSIBLE", f"{verb_name} cannot be reversed")
        comp_verb_name = COMPENSATIONS[verb_name]["verb"]
        comp_verb = WRITE_VERBS.get(comp_verb_name)
        proposal_id = uuid4().hex[:16]
        state.proposals[proposal_id] = {"verb": comp_verb_name, "args": comp_args}  # the reversal, not yet committed
        preview = comp_verb.preview(comp_args) if comp_verb is not None else {"en": f"reverse {verb_name}", "ar": f"عكس {verb_name}"}
        return _envelope(
            "PROPOSAL",
            env,
            {
                "outcome": "proposal",
                "id": proposal_id,
                "verb": comp_verb_name,
                "tier": comp_verb.tier if comp_verb is not None else "HIGH",
                "preview": preview,
                "resolved": comp_args,
                "modifiable": [],
                "expires_at": _now(),
            },
        )

    @app.get("/healthz")
    def healthz() -> Response:
        return Response(status_code=200)

    @app.get("/nil/v0.1/describe")
    def describe() -> dict[str, Any]:
        """Discovery handshake (no auth): what this adapter speaks + live readiness of each
        native target. Lets the kernel/any client connect uniformly — reachable, conformant
        (valid NIL shape), and which targets are provisioned — without backend-specific knowledge."""
        names = sorted({v.doctype for v in WRITE_VERBS.values()})
        targets: dict[str, Any] = {}
        for t in names:
            s = client.schema(t)  # the live skeleton: field list, or None if not provisioned
            targets[t] = {"exists": s is not None, "fields": s or []}
        return {
            "nil": NIL,
            "system": SYSTEM,
            "verbs": sorted(WRITE_VERBS) + sorted(QUERY_VERBS),
            "targets": targets,
        }

    return app
