"""Consume `requirements-manifest.json` (plan §4.4): pre-fill the hidden requirements `scan`
discovered, and apply transport quirks, so `translate.py` stays small and standard-shaped and the
agent never collides with a requirement the toolkit already learned. GENERATED by nilscript scaffold.
"""

from __future__ import annotations

import json
import os
import re
from functools import lru_cache
from pathlib import Path
from typing import Any

_MANIFEST_PATH = Path(__file__).resolve().parent.parent.parent / "requirements-manifest.json"
_ENV_REF = re.compile(r"^\$\{([A-Z][A-Z0-9_]*)\}$")


@lru_cache(maxsize=1)
def _manifest() -> dict[str, Any]:
    if not _MANIFEST_PATH.exists():
        return {}
    return json.loads(_MANIFEST_PATH.read_text(encoding="utf-8"))


def _resolve(value: Any) -> Any:
    """Expand a ${ENV_VAR} instance-value reference from the environment; pass others through."""
    if isinstance(value, str):
        match = _ENV_REF.match(value)
        if match:
            return os.environ.get(match.group(1), "")
    return value


def overlay_requirements(verb: str, native: dict[str, Any]) -> dict[str, Any]:
    """Fill the verb's hidden requirements (from instance_values/env) into the native doc so the
    agent never collides with a requirement `scan` already learned (plan §4.4). Returns a new dict.

    - `required_scalar` / `required_nested` -> a top-level field on the doc.
    - `required_on_line` -> the field is injected into every line of the doc's line container
      (default key `items`; override per-verb with `line_container` in the manifest).

    Only fills where the translation left a hole, and only when an instance value resolves to a
    non-empty value — a structural-only manifest (no instance_values set) overlays nothing.
    """
    entry = _manifest().get("verbs", {}).get(verb, {})
    instance = entry.get("instance_values", {})
    line_container = entry.get("line_container", "items")
    out = dict(native)
    for req in entry.get("hidden_requirements", []):
        field = req.get("field")
        if not field or field not in instance:
            continue
        value = _resolve(instance[field])
        if value in (None, ""):
            continue
        if req.get("kind") == "required_on_line":
            lines = out.get(line_container)
            if isinstance(lines, list):
                out[line_container] = [
                    {**line, field: line.get(field) or value} if isinstance(line, dict) else line
                    for line in lines
                ]
        elif not out.get(field):
            out[field] = value
    return out


def apply_transport_quirks(client: Any) -> None:
    """Apply manifest transport quirks to the system client if it supports them (plan §4.4).

    e.g. `no_expect_100_continue` -> ask the client to drop the `Expect: 100-continue` header that
    tripped the live ERPNext build (HTTP 417). A client that does not expose the hook is left as-is.
    """
    quirks = {q.get("quirk") for q in _manifest().get("transport_quirks", [])}
    if "no_expect_100_continue" in quirks and hasattr(client, "drop_expect_100_continue"):
        client.drop_expect_100_continue()
