"""Minimal correctness state — idempotency ledger + proposal store + per-workspace sequence.

Never business state (that lives in the System of record). GENERATED by nilscript scaffold.
"""

from __future__ import annotations

from typing import Any


class ShimState:
    def __init__(self) -> None:
        self.proposals: dict[str, dict[str, Any]] = {}  # proposal_id -> {verb, args}
        self.ledger: dict[str, dict[str, Any]] = {}  # idempotency_key -> STATUS body
        self.executed: set[str] = set()  # proposal_ids that reached a committed write
        self.compensations: dict[str, dict[str, Any]] = {}  # compensation_token -> {verb, result}
        self._seq: dict[str, int] = {}

    def next_sequence(self, workspace: str) -> int:
        self._seq[workspace] = self._seq.get(workspace, 0) + 1
        return self._seq[workspace]
